### PR TITLE
show own calendars if enabled property is undefined

### LINKED ISSUE #291: Pre-enable default calendar
[It was a bit confusing](https://github.com/owncloud/calendar/issues/287) before I realized that I had to choose the default calendar to show all the events.

It would be better it it was selected per default.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/291

### CODE REVIEW

**Comment by georgehrke** [comment]
please review @jancborchardt

**Comment by jancborchardt** [comment]
@georgehrke rule #1 of pull requests: Mention the people who were mainly involved in the relevant issues so they review it. :) So @enoch85 @raimund-schluessler @blizzz please also help reviewing :)

**Comment by georgehrke** [comment]
(This patch requires latest master and can't be applied to 1.2.2)

**Comment by jancborchardt** [comment]
@georgehrke how can this be best tested?

**Comment by georgehrke** [comment]
create a new user and make sure the default calendar is enabled
or
Delete the `{http://owncloud.org/ns}calendar-enabled` properties in oc_properties

**Comment by jancborchardt** [comment]
@georgehrke does this also need to be backported?

**Comment by georgehrke** [comment]
No, there are no stable\* branches.
Releases are made from master.

**Comment by georgehrke** [comment]
Will package a new release in the next couple of days :)

**Comment by jancborchardt** [comment]
Ok, great!

**Pull request merged**
