### PR TITLE
Always test stable branches

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by georgehrke** [comment]
GRMPF, there are not supposed to be stable branches :confused:

**Comment by georgehrke** [comment]
@karlitschek @cmonteroluque Please remove the calendar from the @owncloud-packager script :)

**Comment by nickvergessen** [comment]
why not? those are really helpful, or do you really want one branch that works with all versions?

**Comment by georgehrke** [comment]
yes, that's also the way it works for news and mail

**Comment by georgehrke** [comment]
We discussed this here: https://github.com/owncloud/calendar/issues/112

**Comment by karlitschek** [comment]
i removed it from the branching script.

**Comment by georgehrke** [comment]
thx :)

**Comment by ghost** [comment]
stable7 build script fixed to work with archive repositories for calendar and contacts

**Pull request closed without merging**
