### PR TITLE
L10n cleanup

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by georgehrke** [comment]
How to test this?

**Comment by DeepDiver1975** [comment]
> How to test this?

there is not much to test - php translation files have been use in oc6 (or 7) and earlier

**Comment by DeepDiver1975** [comment]
will rebase ....

**Comment by DeepDiver1975** [comment]
rebased - we should merge this asap - the next transifex sync will cause a conflict again :wink:

**Comment by georgehrke** [comment]
@DeepDiver1975 Does this also cover the translations used the templates itself?
e.g. https://github.com/owncloud/calendar-rework/blob/master/templates/part.settings.php#L31

**Comment by DeepDiver1975** [comment]
Yes. On Server side translations are loaded from the json files.

**Pull request merged**
