### PR TITLE
WIP: use uibModal for events editor

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar-rework/issues/74

### CODE REVIEW

**Comment by georgehrke** [comment]
@raghunayyar The html is now appended to the fc event dom element. please style the popover :)

**Comment by georgehrke** [comment]
@raghunayyar What's the state on the popover? :)

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/calendar-rework/issues/74

**Comment by georgehrke** [comment]
let's include https://github.com/owncloud/calendar-rework/pull/78 here

**Comment by georgehrke** [comment]
@raghunayyar please add:
- [ ] timezone inputs to both popover and sidebar (just as in #78)
- [ ] add a general tab with description and categories to the sidebar

**Comment by raghunayyar** [comment]
> add a general tab with description and categories to the sidebar

I don't want another general tab, it seems absurd. The only tabs should be attendees and alarms. Description should come on the top with the other details, before the tabs.

**Comment by georgehrke** [comment]
fine with me, those fields just need to be there :)

**Comment by DeepDiver1975** [comment]
Does this include the actual save via webdav as well?

**Comment by georgehrke** [comment]
> Does this include the actual save via webdav as well?

Not yet, but we can already generate an ical from the editors result and the VEventsService already provides a create method.

**Comment by DeepDiver1975** [comment]
> Not yet, but we can already generate an ical from the editors result and the VEventsService already provides a create method.

Can I ask you to 'quickly' add the PUR request? :wink:

**Comment by georgehrke** [comment]
> PUR

?

**Comment by DeepDiver1975** [comment]
PUT :Wink:

**Comment by georgehrke** [comment]
closing in favor of #117

**Comment by georgehrke** [comment]
git wasn't too happy about moving the build folder's content to js/. Rebasing just threw up too many issues. It was easier to just create a new branch and cherry-pick the commits onto it.

**Pull request closed without merging**
