### PR TITLE
Adds spinner to the sidebar before the calendars load.

### PR DESCRIPTION
**Pull request by raghunayyar**
A fix for https://github.com/owncloud/calendar-rework/issues/4

We always had a loader in place, just that we never called it in our template.
Have a look @georgehrke

### CODE REVIEW

**Comment by georgehrke** [comment]
Two things:
- [ ] I think the spinner is far to big. should not be bigger than an list-item imho
- [ ] there is some time span between the server answers the request and the list is rendered. The list should be rendered first thing once the request was answered, please check.

**Comment by georgehrke** [comment]
- [ ] There is a spinner above fullcalendar, please remove it.

**Comment by georgehrke** [comment]
I changed this pr, looks good from my pov now.
please review and feel free to merge afterwords.

**Comment by raghunayyar** [comment]
Works for me, I also see this as faster than it was previously. :+1: x 2.

**Pull request merged**
