### PR TITLE
WIP : Removes bogus 3rdparty, updates bower

### PR DESCRIPTION
**Pull request by raghunayyar**

### CODE REVIEW

**Comment by raghunayyar** [comment]
This is currently breaking the date-picker functionality.

**Comment by georgehrke** [comment]
@DeepDiver1975 The question here is if we fix the date picker here or accept that it will be broken for a few days and fix it once the dav branch was merged. The current date picker should have never been merged, because it relies on a patched 3rdparty lib. Therefore you see the CalendarModel DI error.

**Comment by DeepDiver1975** [comment]
> The question here is if we fix the date picker here or accept that it will be broken for a few days and fix it once the dav branch was merged.

I'd vote for merge and move on - better have one 'little' piece broken then the whole app :wink: 

But let me first fix the failing tests - it's failing because angular is on 1.3 and angular-mocks is on 1.4

I'll downgrade mocks ...

**Comment by georgehrke** [comment]
> I'll downgrade mocks ...

awesome, thx

**Comment by raghunayyar** [comment]
I love you guys.

**Pull request merged**
