### PR TITLE
Implemented until recurrence feature

### PR DESCRIPTION
**Pull request by Julian1998**
ToDo: Init ocdatetimepicker with until moment

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please add test instructions and scenarios - what has been tested already - what not.
THX

**Comment by DeepDiver1975** [comment]
> Please add test instructions and scenarios - what has been tested already - what not.
> THX

general comment for the future to let the team know whats going on ...

**Comment by DeepDiver1975** [comment]
works pretty good besides the fact that the until date is not displayed when opening an existing event ....

**Comment by Julian1998** [comment]
Instructions:

1. create a new event
2. click on more...
3. go to repeating 
4. create a new recurrence with the ending option on date
5. select a date

Possible scenarios:
1. creating a new event with until ending option
2. modifying the current ending option from never/count to until


Both scenarios work fine in Chrome

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
