### PR TITLE
Updates 3rdparty

### PR DESCRIPTION
**Pull request by raghunayyar**

### CODE REVIEW

**Comment by georgehrke** [comment]
keepings deps up-to-date always makes sense.

will test asap.
btw, we should have these dependencies button in our read me, that tells you, if deps are outdated

**Comment by raghunayyar** [comment]
Sure, can you make a PR for that?

**Comment by georgehrke** [comment]
Yes, will create some ticket for me

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar-rework/issues/56

**Comment by georgehrke** [comment]
:+1:

**Comment by georgehrke** [comment]
let's wait for the tests first

**Pull request merged**
