### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by georgehrke**
@DeepDiver1975 Can you please help with setting up scrutinizer and travis? Thx :smiley:

### CODE REVIEW

**Comment by raghunayyar** [comment]
@georgehrke please include the names of the maintainers in the README.md, it's easier for people to reach out that way.

**Comment by georgehrke** [comment]
added a maintainers list, only one thing is left:
- [ ] update travis and scrutinizer links

**Comment by raghunayyar** [comment]
Some love here @DeepDiver1975 :)

**Comment by DeepDiver1975** [comment]
https://scrutinizer-ci.com/g/owncloud/calendar-rework/

**Comment by DeepDiver1975** [comment]
https://travis-ci.org/owncloud/calendar-rework/

**Comment by georgehrke** [comment]
thanks a lot :-)

**Comment by raghunayyar** [comment]
I think this can be merged now @georgehrke

**Pull request merged**
