### PR TITLE
Generate caldav link properly 

### LINKED ISSUE #23964: Wrong caldav URL displayed in web-frontend
Owncloud web-interface reports wrong (?) Caldav URL:

https://myhost/owncloud/remote.php/dave.php/dav/calendars/username/contact_birthdays/

Using this URL Caldav access is denied.

Using a slightly modified URL (without "/dave.php") makes things work for me.

https://myhost/owncloud/remote.php/dav/calendars/username/contact_birthdays/

Maybe this is just a simple typo, that can be fixed easily?

### Steps to reproduce
1. Install OC 9.0.1
2. Run thunderbird (38.6.0) with Lightning (4.0.5.2) (on Ubuntu 14.04)
3. Try to add Calendar URL to Lightning

### Expected behaviour
Sync with owncloud calendar should start

### Actual behaviour
Sync fails - Server reports error 503

### Server configuration
**Operating system**:
Ubuntu 14.04.4 (x86_64)

**Web server:**
Apache 2.4.7

**Database:**
mysql 5.5.47
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
Fresh install - old data migrated from 8.2

**Where did you install ownCloud from:**
Downloaded .tar.bz2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - user_external

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '<instanceid>',
  'passwordsalt' => '<salt>',
  'datadirectory' => '/proj.stand/owncloud.data',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
  ),
  'trusted_domains' => 
  array (
    0 => 'www.linux-ng.de',
  ),
  'secret' => '<longsecret>',
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:3306',
  'dbuser' => 'owncloud',
  'dbpassword' => 'mypassowrd',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

NO

**Are you using encryption:** yes/no

NO

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- fixes https://github.com/owncloud/core/issues/23964

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@georgehrke mind taking a look once you are back from :us:

**Comment by georgehrke** [comment]
Why no window location protocol?

Please excuse my brevity and typos.

**Comment by DeepDiver1975** [comment]
Origin is protocol + host

**Comment by georgehrke** [comment]
ok, never mind then 🙈 

Will test later today and merge

**Comment by georgehrke** [comment]
👍

**Pull request merged**
