### PR TITLE
introduce more menu in calendar list

### PR DESCRIPTION
**Pull request by georgehrke**
ToDo:
- [x] show actions all the time

### CODE REVIEW

**Comment by georgehrke** [comment]
@jancborchardt I can't seem to figure out, why the actions only appear on hover. I can't find any CSS rules that would imply this. I'm probably missing the obvious :confused:

**Comment by georgehrke** [comment]
@jancborchardt Should the icons (share and ...) be visible 24/7?

**Comment by jancborchardt** [comment]
@georgehrke I’d say yes maybe let’s try to show them all the time. That’s why I also said that it might be good to put share in the dropdown as well. Then again, sharing is also needed as an indicator if it has been shared (as done in the Files app) so we kinda need it outside.

After this short introspective: Yeah let’s show them all the time, and use the share icon as indicator as well, just like in the Files app with the actions on each file row. :)

**Comment by jancborchardt** [comment]
@georgehrke at the same time, please work on standardizing this menu with @PVince81 and @BernhardPosselt, documenting the markup at https://doc.owncloud.org/server/9.0/developer_manual/app/css.html#standard-layout

**Comment by raghunayyar** [comment]
@georgehrke https://github.com/owncloud/calendar/blob/master/css/calendarlist.css#L120 if you give width: 120px or something over here, you can see the actions all the time. Let me know if it works. :)

**Comment by georgehrke** [comment]
I figured out that it had something to do with the width, but no width being assigned at all was too obvious :see_no_evil:

**Comment by georgehrke** [comment]
but assigning a width doesn't work for me. The actions are still 0x0 for some reason

**Comment by georgehrke** [comment]
got it

**Comment by raghunayyar** [comment]
Works for me. :+1:

**Comment by georgehrke** [comment]
pass locally -> merge

**Comment by jancborchardt** [comment]
@georgehrke can you document the markup then now at the docs page I referenced above? And work with @BernhardPosselt on standardizing it, in case it’s different from what’s done in the News app or Files app?

**Comment by jancborchardt** [comment]
@georgehrke did the documentation of the markup happen, as mentioned above? cc @BernhardPosselt @owncloud/javascript

**Pull request merged**
