### PR TITLE
Webcal support

### LINKED ISSUE #132: support for webcal
- [ ] add a subscription service
- [ ] for now query subscriptions on load (using render event with static option)

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/132

### CODE REVIEW

**Comment by georgehrke** [comment]
developer tools - http --owncloud dev-index php-apps-calendar- chromium today at 2 19 09 pm

To check: 
why is it d:collection and cal:calendar instead of the being replaced with the proper xml namespaces?

**Comment by georgehrke** [comment]
why is it d:collection and cal:calendar instead of the short namespace being replaced with the long one?

developer_tools_-_http_--owncloud_dev-index_php-apps-calendar-_chromium__today_at_8_57_22_pm

@evert @PVince81 Is this the intended behavior of davclient.js or is it a bug?
(If it's a bug, I can look into it :wink:)

**Comment by evert** [comment]
It's a bug!

**Comment by PVince81** [comment]
Strange... it seems to work with the file list, see how it's checked here: https://github.com/owncloud/core/blob/v9.0.1/core/js/files/client.js#L286

Maybe the response contains newlines and the parsing fails for some reason

**Comment by PVince81** [comment]
Or it's because there is more than one element, I never tested with more than one :frowning:

**Comment by georgehrke** [comment]
While looking into fixing this I also noticed that `supported-calendar-component-set` was broken all the time. cc @DeepDiver1975 @raimund-schluessler 

developer_tools_-_http_--owncloud_dev-index_php-apps-calendar-_chromium__today_at_2_17_52_pm

**Comment by georgehrke** [comment]
I would propose to replace these blocks with an array like:

```
{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set: [
{
  propName: '{urn:item:params:xml:ns:caldav}comp',
  attributes: {
    name: 'VEVENT'
  }
},
{
  propName: '{urn:item:params:xml:ns:caldav}comp',
  attributes: {
    name: 'VTODO'
  }
}
],
```

Do we lose any data with this approach or is it fine?

**Comment by georgehrke** [comment]
And especially when it comes to these nested acl blocks we need a proper recursive solution:

``` xml
    <d:acl>
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/admin/</d:href>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:read/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/admin/</d:href>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:write/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
    </d:acl>
```

**Comment by PVince81** [comment]
@georgehrke mind having a look at the lib and submit a PR there if you find a fix that works ?

**Comment by georgehrke** [comment]
Yes :)

just wanted to get feedback on my approach suggested in https://github.com/owncloud/calendar/pull/443#issuecomment-215065717

**Comment by georgehrke** [comment]
closing in favor of https://github.com/owncloud/calendar/pull/631

**Pull request closed without merging**
