### PR TITLE
Add an indication to the calendar list when a calendar is shared

### PR DESCRIPTION
**Pull request by MathieuSchopfer**
This PR is related to issue #431.

### CODE REVIEW

**Comment by MathieuSchopfer** [comment]
The work for this PR is done. It can go in review.

**Comment by georgehrke** [comment]
Thx a lot! :)
Will take a look asap

**Comment by georgehrke** [comment]
How did you test this without updating the app.js 🙈 😉

**Comment by georgehrke** [comment]
I squashed your commits, generated the app.js and adopted the opacity from the files app.
Closing in favor of https://github.com/owncloud/calendar/pull/571

**Comment by MathieuSchopfer** [comment]
@georgehrke I did update `app.js`, I just did not commit it.

**Comment by georgehrke** [comment]
okay :)

**Pull request closed without merging**
