### PR TITLE
get caldav properties out of calendar model

### LINKED ISSUE #314: Edit button is not shown for own calendars
### Steps to reproduce
1. Install OC 9.0.0 and latest calendar master
2. Create a new calendar or have a look at an existing one
3. Hover calendar, edit button should be shown
### Expected behaviour

Edit button does not show up
### Actual behaviour

Edit button does not show up (only share, download and delete are visible, see screenshot)
### Server configuration

Current Debian running on Virtual box

**Web server:**
Apache 2.4.10

**Database:**
Maria DB 10.0.22-MariaDB-0+deb8u1 - (Debian)

**PHP version:**
5.5 I guess

**ownCloud version:** (see ownCloud admin page)
OC 9.0.0

**Calendar version:** (see ownCloud apps page)
Current master e3b5be1

**Updated from an older ownCloud or fresh install:**
Fresh

Nothing significant in the logs.

The reason for this is, that `calendar.owner` is not set since at https://github.com/owncloud/calendar/blob/master/js/app/models/calendarmodel.js#L114 `owner` equals `/owncloud/remote.php/dav/principals/users/raimund` which does not fulfill `owner.startsWith('/remote.php/dav/principals/users/')` at https://github.com/owncloud/calendar/blob/master/js/app/models/calendarmodel.js#L115

I hope this helps.

### LINKED ISSUE #316: remove caldav property names from calendarmodel

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/316
fixes https://github.com/owncloud/calendar/issues/314

### CODE REVIEW

**Comment by georgehrke** [comment]
@raimund-schluessler should also fix #314

**Comment by georgehrke** [comment]
wait, it doesn't at the moment :see_no_evil:

**Comment by georgehrke** [comment]
it should now

**Comment by raimund-schluessler** [comment]
Fixes #314 :+1:

**Comment by raimund-schluessler** [comment]
Btw. what is it good for to "get caldav properties out of calendar model" ?

**Comment by georgehrke** [comment]
There should be a distinct separation between the calendar Model and the CalendarService. The calendarModel should just be a calendarModel, it doesn't need to know that the property was once called `{http://apple.com/ns/ical/}calendar-color`.
Having all those namespace strings in the CalendarService and CalendarModel is duplicate code.
I would consider the solution in 1.0 bad design.

**Comment by georgehrke** [comment]
This is not only for the sake of good quality code, but will also come very handy when we implement webcal. By then we will have two sources for calendars, the CalendarService and the yet to be implemented SubscriptionService.

**Comment by raghunayyar** [comment]
Please rebase and merge. This is long due.

**Pull request merged**
