### PR TITLE
WIP : Autocompletion of Location.

### PR DESCRIPTION
**Pull request by raghunayyar**
Have a look @georgehrke.

### CODE REVIEW

**Comment by georgehrke** [comment]
please rebase

**Comment by georgehrke** [comment]
lets wait for #113 to be merged

**Comment by georgehrke** [comment]
really needs a rebase :see_no_evil:

**Comment by raghunayyar** [comment]
There is no point of doing this now, I will do a fresh PR.

**Comment by georgehrke** [comment]
please see my comment in https://github.com/owncloud/calendar-rework/issues/65#issuecomment-181996534

**Pull request closed without merging**
