### PR TITLE
fix issue with creating events

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar-rework/issues/246

please review @raimund-schluessler

### CODE REVIEW

**Comment by raimund-schluessler** [comment]
Creating of events is possible now, editor shows up and event is saved.

But now I see
```
Error: fcEvent is null
$scope._initializeEventEditor/<@http://192.168.56.2/owncloud/apps/calendar/js/public/app.js?v=a22d47f2e3ec6b4b78344815cc1f3fdb:272:5
```
when clicking in the calendar.

**Comment by georgehrke** [comment]
@raimund-schluessler please retest

**Comment by raimund-schluessler** [comment]
:+1:
No javascript errors, events are created fine.

**Comment by georgehrke** [comment]
Sorry for the inconvenience

**Comment by raimund-schluessler** [comment]
Not to worry, thanks for fixing it :smiley:

**Pull request merged**
