### PR TITLE
WIP: Migrate import to dav

### PR DESCRIPTION
**Pull request by georgehrke**
Using the dav backend requires some changes to the import.
Previously there was an REST API endpoint to which one could send an ics with multiple objects.
This doesn't work with dav. We have to import objects one at a time.

The newly introduced `SplitterService` is taking care of splitting up the big ics blobs.

fyi @raghunayyar

### CODE REVIEW

**Comment by georgehrke** [comment]
There is one remaining issue I would like to resolve:

ICS files can contain events, todos and journals. Calendars may not support all three types.
So the question is what to do:
- If e.g. a user tries to import an ics with events and todos:
 - 1. only show calendars that support at least events and todos (if none, there is still the new calendar option)
 - 2. show all calendars but add a warning that not all objects from the ics will be imported

**Comment by raghunayyar** [comment]
@georgehrke can we show what precisely cant be imported?

**Comment by georgehrke** [comment]
theoretically yes, but that means implementing some parsing logic for todos and journals, which will be quite some work.

another issue is how to notify the user about events (or todos or journals) rejected by the server.

**Comment by raghunayyar** [comment]
cc @jancborchardt

**Comment by karlitschek** [comment]
awesome work guys. :-)
do you have concrete plans already how the migration story for people moving from owncloud 8.2 to 9.0 looks like?
idealy migration is fully automatic. so the new calendar or maybe owncloud core detects that old calendar db tables exist and automatically moves data over without manual work
what do you think?
@DeepDiver1975

**Comment by georgehrke** [comment]
> do you have concrete plans already how the migration story for people moving from owncloud 8.2 to 9.0 looks like?

I agree that it should ideally be done fully automatic. AFAIK the calendar table is pretty much the same, but the objects table is a bit different. It now contains firstoccurrence and lastoccurrence, so we have to parse every single object :/

So maybe some extra upgrade routine after the actual update to ownCloud 9.

**Comment by karlitschek** [comment]
Works for me as long as this additional upgrade routine is executed automatically without a manual step by the user.
What do you think?

**Comment by georgehrke** [comment]
Hm, maybe an additional step for the admin?

**Comment by karlitschek** [comment]
well. the goal ist that users upgrade from 8.2 to 9.0 and everything works without any manual work and configuration change and manual script execution or documentation reading.
This is the goal.

**Comment by DeepDiver1975** [comment]
Calendar and contacts migration is a core task. I'm working on a solution. Wip PR is open in core.

**Comment by georgehrke** [comment]
> Wip PR is open in core.

Can you point us there? :)

**Comment by DeepDiver1975** [comment]
> Can you point us there? :)

https://github.com/owncloud/core/pull/21333

**Comment by karlitschek** [comment]
@DeepDiver1975 Awesome :-)

**Comment by georgehrke** [comment]
@jancborchardt any opinion? :)

**Comment by jancborchardt** [comment]
@georgehrke see the discussion in the core issue. I agree with @karlitschek that it's important to be as automatic as possible. However we need to gauge to which point this is possible.

**Comment by georgehrke** [comment]
@jancborchardt I mean the actual issue mentioned in the top of this issue ;)

https://github.com/owncloud/calendar-rework/pull/110#issuecomment-170279268

**Comment by jancborchardt** [comment]
I'd go for option 2 as it provides proper feedback.

**Comment by georgehrke** [comment]
Okay, will go for that :)

**Comment by georgehrke** [comment]
@raghunayyar please check

**Comment by DeepDiver1975** [comment]
Tested import of a single event :+1:

**Comment by DeepDiver1975** [comment]
bulk import works as well :+1: 

merge from my pov

**Comment by DeepDiver1975** [comment]
hmm .. bloody php builtin webserver doesnot support MKCALENDAR :imp:

**Pull request merged**
