### PR TITLE
Make date and time more visible

### LINKED ISSUE #459: Opacity is too much
### Steps to reproduce

Open the calendar in webUI
### Expected behaviour

Opacity should be less
### Actual behaviour

Opacity is to much and makes the dates and time almost invisible

deepinscreenshot20160413000757
### Server configuration

**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.4
**Database:**
Mysql 5.5
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Calendar version:** (see ownCloud apps page)
1.1
**Updated from an older ownCloud or fresh install:**
Updated
**Signing status (ownCloud 9.0 and above):**
No errors
### Client configuration

**Browser:**
Version 49.0.2623.112 (64-bit) Chrome
**Operating system:**
Deepin 15 (Debian)
**CalDAV-clients:**
DavDroid
### Logs

No logs

cc @jancborchardt

### PR DESCRIPTION
**Pull request by enoch85**
Fixes #459 

cc @jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
@enoch85 can you show a before-after screenshot please so it’s easier to review for prospective design contributors? :)

**Comment by enoch85** [comment]
@jancborchardt Sure.

**Before**
deepinscreenshot20160415184956

**After**
deepinscreenshot20160415185441

**Comment by jancborchardt** [comment]
I’m fine with fixing the time display, but the date I think is okay as it is now.

**Comment by enoch85** [comment]
@jancborchardt Yeah our user group isn't 40+ right? ;)

**Comment by georgehrke** [comment]
@jancborchardt 👍?

**Comment by raghunayyar** [comment]
Merging this!

**Pull request merged**
