### PR TITLE
use random color as fallback when importing

### LINKED ISSUE #390: Imported calendars have same color
I just imported two calendars from .ics files and both have the same dark blue color.

For any new calendar or imported calendar, the color should automatically be set to the first unused color.
Also, we should not have this dark blue, still dark blue and the dark grey … they are much too dark and not distinguishable either. For example, we don’t have any green color at all.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/390

### CODE REVIEW

**Comment by aspdye** [comment]
Nice idea :+1:

**Comment by raghunayyar** [comment]
XD

**Comment by skjnldsv** [comment]
👍

**Comment by georgehrke** [comment]
@skjnldsv randColour fails silently on ownCloud 9 and blocks everything 😕

**Comment by skjnldsv** [comment]
Hum, any informations to add?
Why does it fail?

**Comment by skjnldsv** [comment]
Is it because oc9 doesn't have the .toHsl function? ^^

**Pull request merged**
