### PR TITLE
Adds overflow y on the app sidebar.

### LINKED ISSUE #395: scrolling in sidebar broken
not possible to see everything

### PR DESCRIPTION
**Pull request by raghunayyar**
Fixes https://github.com/owncloud/calendar/issues/395. This is an important fix, we should get it in asap. :)

### CODE REVIEW

**Comment by georgehrke** [comment]
please review @jancborchardt @mar1u5

**Comment by MariusBluem** [comment]
It seems to work now for me 👍 
We've also talked about that @jospoortvliet ... Maybe you could also look, wheter this is fixed for you now 😁

**Comment by georgehrke** [comment]
works perfect 👍

**Comment by georgehrke** [comment]
@raghunayyar Does this make https://github.com/owncloud/calendar/pull/670 obsolete?

**Comment by raghunayyar** [comment]
Yes, closing that.

**Pull request merged**
