### PR TITLE
Overall timezone display fixes

### LINKED ISSUE #154: When disabling allday and timezone is null, set it to defaulttimezone

### LINKED ISSUE #155: Show timezone in popover
If the timezone differs from defaulttimezone, show the actual timezone of the event.
This doesn't need to be a select like in the sidebar, just a span that displays the selected one.

### LINKED ISSUE #156: show timezone when opening sidebar if selected one is not defaulttimezone

### LINKED ISSUE #160: group timezones by continent and replace _ with space in displayname

### LINKED ISSUE #171: add timezone filter to display timezone in a more user-friendly way
e.g. New York (America) instead of America/New_York

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #171
fixes #160 
fixes #156 
fixes #155 
fixes #154

### CODE REVIEW

**Comment by georgehrke** [comment]
rebased

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-02-16 11-25-51

bildschirmfoto von 2016-02-16 11-27-21

bildschirmfoto von 2016-02-16 11-27-43

bildschirmfoto von 2016-02-16 11-28-10

bildschirmfoto von 2016-02-16 11-28-33

**Comment by georgehrke** [comment]
@DeepDiver1975 What are you trying to tell me? :)

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-02-16 11-29-09

bildschirmfoto von 2016-02-16 11-29-24

bildschirmfoto von 2016-02-16 11-30-01
bildschirmfoto von 2016-02-16 11-30-27
bildschirmfoto von 2016-02-16 11-30-46

**Comment by georgehrke** [comment]
- [ ] remove second underscore

**Comment by DeepDiver1975** [comment]
And there is a dot missing after all these St ...

**Comment by georgehrke** [comment]
> not really a name

It actually is ;)
https://en.wikipedia.org/wiki/Longyearbyen

**Comment by georgehrke** [comment]
- [ ] remove dashes from name

**Comment by georgehrke** [comment]
- [ ] replace `St` with `St.`

**Comment by georgehrke** [comment]
> too much sashes
bildschirmfoto von 2016-02-16 11-29-09

It's actually called Port-au-Prince
https://en.wikipedia.org/wiki/Port-au-Prince

**Comment by DeepDiver1975** [comment]
> It actually is ;)
> https://en.wikipedia.org/wiki/Longyearbyen

haha - looked like 'Long year by en'

**Comment by DeepDiver1975** [comment]
> It's actually called Port-au-Prince

but then we have a few whitespaces too much - right?

**Comment by georgehrke** [comment]
> but then we have a few whitespaces too much - right?

- [ ] I will check

**Comment by DeepDiver1975** [comment]
let me play with this during lunch time :wink:

**Comment by georgehrke** [comment]
sure :)

**Comment by DeepDiver1975** [comment]
@raghunayyar @georgehrke Why is Porto-au-Prince in this list with slashes and not with dashes?
https://github.com/owncloud/calendar-rework/blob/master/js/app/service/timezonelistprovider.js#L197

There is basically no way to differentiate 

```js
			'America\/North_Dakota\/New_Salem',
			'America\/Port\/Au\/Prince',

**Comment by georgehrke** [comment]
> Why is Porto-au-Prince in this list with slashes and not with dashes?

That's a bug, I extracted the timezone names from the file names in timezones/.
We definitely need a better solution for this in the future. Like greping for the line with `TZID:...`

**Comment by georgehrke** [comment]
Actually we should validate that list, to make sure all entries map to a proper timezone.
Should be fairly easy with a test.
Let me open a ticket for that, nothing we have to fix before alpha2

**Comment by DeepDiver1975** [comment]
I assume there is some mapping in place to get the proper timezone ics file for a given timezone in that list. Where is that happening?

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar-rework/blob/master/controller/viewcontroller.php#L94

**Comment by DeepDiver1975** [comment]
Okay - porto-au-prince is broken - it cannot load the ics file

**Comment by georgehrke** [comment]
because in the name it's Au, it should be au.

**Comment by DeepDiver1975** [comment]
> because in the name it's Au, it should be au.

with the slashes in the name it was trying to load 
http://localhost:8888/index.php/apps/calendar/v1/timezones/AMERICA/PORT/AU/PRINCE.ics

**Comment by DeepDiver1975** [comment]
@georgehrke @raghunayyar are you okay with my changes?

**Comment by georgehrke** [comment]
will review and merge afterwords

**Pull request merged**
