### PR TITLE
Ruin app.js to provide support for Safari 9

### PR DESCRIPTION
**Pull request by georgehrke**

### CODE REVIEW

**Comment by MariusBluem** [comment]
Lets Test :wink:

**Comment by MariusBluem** [comment]
After superficial testing I have to say, that it is still not working 😢

**Comment by MariusBluem** [comment]
`SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
(anonyme Funktion) — app.js:393
`

**Comment by georgehrke** [comment]
Did you just apply this patch to 1.3 or git?

**Comment by MariusBluem** [comment]
I've downloaded the branch 😁

**Comment by georgehrke** [comment]
Okay, maybe some caching issue?

**Comment by georgehrke** [comment]
There is definitely no `const` in that line
https://github.com/owncloud/calendar/blob/thanks_safari/js/public/app.js#L393

**Comment by MariusBluem** [comment]
...ahh 😒 The Cache. Now it works 😅 Sorry... 👍 

After an superficial test (creating events, ...) I can say that it works for me 💪

**Comment by georgehrke** [comment]
awesome :)
Thx for testing.
Preparing 1.3.1 ...

**Pull request merged**
