### PR TITLE
hide events after deleting calendar

### LINKED ISSUE #645: Deleting calendar doesn't refresh calendarview to hide events
### Steps to reproduce
1. Add events to a calendar
2. Delete the calendar while events are on that view
### Expected behaviour

Events from that calendar should be gone
### Actual behaviour

Events stayed on the calendar view, until I refreshed the page

[...]
#### ownCloud log (data/owncloud.log)

Nothing relevant
#### Browser log

No errors.

### LINKED ISSUE #656: Hiding a calendar needs a refresh after creation to work
### Steps to reproduce
1. Create a calendar or use an existing calendar
2. Create an event for this calendar
3. Toggle (hide) the calendar visibility
### Expected behaviour

Events should be hidden
### Actual behaviour

Events are not hidden.

When the calendar is shown again, the same event is added again.
oc_calendar_duplication_bug

This doesn't happen with a refresh after the event is created.

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/645, fixes #656

please review @tcitworld

### CODE REVIEW

**Comment by tcitworld** [comment]
Partly works :
- Creating a calendar
- Creating an event
- Refreshing the page
- Deleting calendar works properly : event disappears

but without refreshing the page, it doesn't.

**Comment by georgehrke** [comment]
okay, will check

**Comment by tcitworld** [comment]
> but without refreshing the page, it doesn't.

Should be the same issue than https://github.com/owncloud/calendar/issues/656

**Comment by georgehrke** [comment]
please check again @tcitworld :)

**Comment by tcitworld** [comment]
Well I can't test anymore because there's another issue : events created from a calendar you just created don't show up after their creation (but there are correctly displayed after a page refresh)

**Comment by georgehrke** [comment]
Ah, i know why
On it

**Comment by georgehrke** [comment]
ping @tcitworld 
Next try ;P

**Comment by tcitworld** [comment]
Seems to work perfectly ! :+1:

**Pull request merged**
