### PR TITLE
WIP: implement search

### LINKED ISSUE #101: implement a search function

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/101

What I learned so far:
- We definitely need custom attributes for paging
- We need to be able to search in the calendar home instead of sending individual requests for all calendars
  cc @DeepDiver1975 @raimund-schluessler

### CODE REVIEW

**Comment by georgehrke** [comment]
- [ ] Only search title for now? Performance sucks with title, description, location, attendee name, attendee email

**Comment by aspdye** [comment]
Yeah :rocket: But how would we solve the Performance issues in the Future :grin:

**Comment by georgehrke** [comment]
All your calendars are inside a single folder, the calendar home. When it comes to ownCloud, this folder is  `remote.php/caldav/calendars/username/`. Inside are other folders like private, work, whatsoever. These are your actual calendars. Right now we have to send search requests to each calendar (private, work, ...).
AFAIK Caldav servers can implement a search method on the calendar home level, so only one request for all calendars. 
But apparently the caldav server of OwnCloud 9 does not have this capabilities. Something we should implement till 9.1 :)

**Comment by aspdye** [comment]
Keep in mind the feature freeze of core 9.1 verry soon :warning: ...how have we done this in the legacy calendar app :confused:

**Comment by georgehrke** [comment]
- [ ] also search webcal feeds

**Comment by georgehrke** [comment]
> We need to be able to search in the calendar home instead of sending individual requests for all calendars

@DeepDiver1975 Do you know if this is just me missing something or is this feature actually not present in our CalDAV interface?

**Comment by MariusBluem** [comment]
What is the current status?

**Comment by georgehrke** [comment]
in development, will not make it into 1.3

**Pull request closed without merging**
