### PR TITLE
Fix import 2

### PR DESCRIPTION
**Pull request by georgehrke**
supersedes https://github.com/owncloud/calendar/pull/627

### CODE REVIEW

**Comment by georgehrke** [comment]
@tcitworld Please check my latest commit.
This way we only reload the calendar in question :)

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/calendar/issues/389

**Comment by georgehrke** [comment]
@tcitworld this fixes https://github.com/owncloud/calendar/issues/628, right?

**Comment by tcitworld** [comment]
Yup. See below. The filename span could do with a little margin-right, though (it sticks to the input next to it).
longfilename

**Comment by georgehrke** [comment]
Okay, I added `...` to make clear a filename is cut off.

**Comment by georgehrke** [comment]
Best solution would probably fixing this in CSS, but we can fix this later.

**Comment by tcitworld** [comment]
You mean keeping the whole file name and using something like `text-overflow: ellipsis;` ?

**Comment by georgehrke** [comment]
Yes, but let's get this in for now.
The CSS for the import dialog needs to be cleaned up anyway 🙈

**Pull request merged**
