### PR TITLE
fix app order

### PR DESCRIPTION
**Pull request by jancborchardt**
The idea is to have the sorting start with: Files, Activity, Gallery, Mail, Contacts, Calendar, and then the rest etc.

Please review @georgehrke @DeepDiver1975

### CODE REVIEW

**Comment by georgehrke** [comment]
Is there some explanation about the order?

**Comment by georgehrke** [comment]
:+1:

**Comment by jancborchardt** [comment]
The explanation is:
- line 1: Files, Activity, Gallery – the apps which are shipped and enabled by default
- line 2: Mail, Contacts, Calendar – the typical personal info mgmt apps, most used (Contacts is before Calendar cause it relates strongly to Mail)
- line 3 etc: everything else (Notes, News, Maps, Music, Bookmarks etc)

cc @owncloud/designers @DeepDiver1975 for reference

**Comment by jancborchardt** [comment]
Rebased, we can merge I guess.

**Comment by skjnldsv** [comment]
Okay!
Are we planning on letting the user choose the order?

**Comment by jancborchardt** [comment]
Nope, not for now at least and I actually don’t really see a reason to do that. (We had discussions about that in the past.) It’s just unnecessary work.
Maybe in the future we can introduce a »sort by most used« but that’s overkill too for now.

**Comment by skjnldsv** [comment]
Agreed!

**Pull request merged**
