### PR TITLE
use user id not the displayname

### LINKED ISSUE #836: Users are unable to create / modify events on the shared calendar
Issue:
- User A creates a calendar and shares it with User B
- User B can see the shared calender, but cann't create or modify events
- Additionally some of the shared calenders aren't showed in "calender" section, but in "subscription"

2017-12-18 10_22_17-spiceworks - tickets ri offen

----------------

Initial Idea was an OC Upgrade vom 8.1 -> 10 AND Migration to 64bit System

Starting at:
- openSUSE 13.1 i586 (32bit)
- ownCloud 8.1.9
- Calendar 0.7.4

----------------

Did the following:
openSuSE 13.1 to 13.2 (32bit) regarding OC 10 dependencies
System is on
- Apache2: 2.4.10-31.1
- MySQL: 5.6.34-2.23.1
- PHP: 5.6.1-89.1

----------------

- Update ownCloud 8.1.x -> 8.2.x
- Update ownCloud 8.2.x -> 9.0.x
ran into this issue: #800
solved it like this:
go to lib/private/integritycheck/checker.php and just returning false in function isCodeCheckEnforced

----------------

ownCloud Update 9.0 -> 9.1 ... using:
sudo -u wwwrun php occ dav:migrate-calenders
sudo -u wwwrun php occ dav:migrate-addressbooks
ran into the same error -> see "calender issue" above ... fixed it the same way

next error - if I try to activate the calender app - "App Folder already exists", so I did:
rename Foldername to Foldername.old (in app Subdirectory)
Installed the App from Webgui again

----------------

ownCloud Update 9.1 -> 10.x ... next error during "sudo -u wwwrun php occ upgrade"
Repair warning: Please install or update the following apps manually or disable them with ... did it:
occ app:disable activity
occ app:disable calendar
occ app:disable filespdfviewer_
occ app:disable filestexteditor_
occ app:disable gallery

updated all apps using webgui

----------------

next step should be the migration from 32bit to 64bit system...
...but at first I've to fix the calender issue!

Calender worked till "9.1 -> 10.x"

----------------

initially this issue was diskussed at https://github.com/owncloud/calendar/issues/830#issuecomment-352350491 which was opened by SimoneCampinoti ... for clearing up the situation (Simone was talking about "non-proprietary users") DeepDiver1975 decided to separate it and forced me to open a new case...

Best,
Mike

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Fixes #836

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
For easy testing:
[calendar.tar.gz](https://github.com/owncloud/calendar/files/1578767/calendar.tar.gz)

**Comment by ittrend4710** [comment]
already tested it - see my remarks in https://github.com/owncloud/calendar/issues/836

**Comment by localguru** [comment]
Doesn't work with 9.1.7 and calender 1.5.4.  Ricardo665 #823 works, but I don't understand why?

**Comment by DeepDiver1975** [comment]
> Doesn't work with 9.1.7 and calender 1.5.4.

no new version of the calendar has been released yet.

**Pull request merged**
