### PR TITLE
Adds styles for sharing

### PR DESCRIPTION
**Pull request by raghunayyar**
Fine tunes the sharing drop-down styles.

Please check @georgehrke and @jancborchardt

### CODE REVIEW

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/calendar/issues/381

**Comment by georgehrke** [comment]
much better than before, but there are still some issues:
- [x] when typing a username the input field "jumps down" a few pixels until the results are loaded
- [x] There is some annoying whitespace in the bottom of the dialog, see:
  calendar_-_owncloud_chromium__today_at_10_56_57_am

**Comment by raghunayyar** [comment]
Will fix this asap.

**Comment by jancborchardt** [comment]
These styles should be in core so they are applied globally.

**Comment by tomneedham** [comment]
> These styles should be in core so they are applied globally.

They would need to be adapted since contacts/calendar use an angular directive to perform the auto completion - but possible :)

**Comment by georgehrke** [comment]
Let's fix the mentioned issues in a  follow up pr.

**Pull request merged**
