### PR TITLE
Update hsl rgb converter in package json file

### LINKED ISSUE #1333: [nightly] Javascript tests pipeline is failing
Build: https://drone.owncloud.com/owncloud/calendar/1983/8/4

```bash
+ make test-js
yarn install
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Error: https://codeload.github.com/kayellpeee/hsl_rgb_converter/tar.gz/3936a3896dd2f45a5c66317aab6f9175c9fde9fb: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:66750:16)
    at Request.emit (events.js:400:28)
    at Request.module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:142287:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:175: node_modules] Error 1
```

### PR DESCRIPTION
**Pull request by S-Panta**
Fixes https://github.com/owncloud/calendar/issues/1333

### CODE REVIEW

**Comment by phil-davis** [comment]
Related issue #1333

**Comment by saw-jan** [comment]
Could you try updating here?
```diff
- 'node_modules/hsl_rgb_converter/converter.js'
+ 'node_modules/hsl_rgb_converter/index.js'
```
https://github.com/owncloud/calendar/blob/6d2e73356ac034afc3ae72616c8357f14e04189e/gulpfile.js#L66

**Comment by S-Panta** [comment]
changed into this repo https://github.com/o-klp/hsl_rgb_converter  and CI is green now. Package.json looks kindof similar to the last one we're using. 
@DeepDiver1975  @phil-davis

**Comment by phil-davis** [comment]
> changed into this repo https://github.com/o-klp/hsl_rgb_converter and CI is green now. Package.json looks kindof similar to the last one we're using.

That was last changed 10 years ago.

Maybe we should fork something into a new owncloud repo that we can control in future, or just add the `converter.js` directly to the calendar repo, and don't have any dependency.

@DeepDiver1975 ?

**Comment by S-Panta** [comment]
If that package is just used for color conversion, will it create a problem even if it was last modified 10 years ago? @phil-davis

**Comment by phil-davis** [comment]
> If that package is just used for color conversion, will it create a problem even if it was last modified 10 years ago?

No problem, if the algorithm is correct it will last forever. The "problem" is more that the repo might suddenly disappear any day - for example, if the GitHub user deletes their account.

Maybe it will be easiest to just commit `converter.js` to this calendar repo, and make sure to leave author comments in it so that the original open-source author(s) are acknowledged.

**Comment by S-Panta** [comment]
The nightly still fails for this calendar app. I think we should work to make ci green either by adding new dependencies or adding the algorithm code snippets.  @phil-davis @DeepDiver1975

**Pull request merged**
