### PR TITLE
Fix display of long titles when calendar is shared

### LINKED ISSUE #636: Shared label overlaps calendar name, is not aligned, calendar 1.3
### Steps to reproduce
1. Share a calendar with a long name with another user
2. Have a look at the shared label
### Expected behaviour

Shared label should not overlap the calendar name, should be vertically aligned with the calendar name
### Actual behaviour

It overlaps and is not aligned, see attached screenshot

sidebar
### Server configuration

**ownCloud version:** 9.0.4

**Calendar version:** 1.3
### Client configuration

**Browser:** Firefox 47.0

**Operating system:** Win 10

### PR DESCRIPTION
**Pull request by tcitworld**
Fixes #636

### CODE REVIEW

**Comment by tcitworld** [comment]
It must also be limited inside the popover.

oc_names_too_big

**Comment by raimund-schluessler** [comment]
I will test this PR, but I didn't got my calendar dev environment running (NPM is giving errors).

**Comment by tcitworld** [comment]
@raimund-schluessler Here is the app.js file (zipped for github) that you need to need to put into `js/public/`
[app.js.zip](https://github.com/owncloud/calendar/files/390157/app.js.zip)

**Comment by georgehrke** [comment]
thx :)

**Comment by jancborchardt** [comment]
Awesome work @tcitworld! :)

**Pull request merged**
