### PR TITLE
create calendars with vtodo by default

### LINKED ISSUE #329: Creating calendars with comps VEvent and VTodo by default
Hello,

   I discuss with @raimund-schluessler about update task list when calendar is created in owncloud 9 with task branch DAVClient. Could you see this : 
[(https://github.com/owncloud/tasks/issues/298)] 

> If you want calendars created in the Calendar app to appear in the Tasks app, you will have to ask the Calendar developers to change https://github.com/owncloud/calendar/blob/master/js/app/service/calendarservice.js#L166 to also specify VTodo.

Thanks for your help

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/329

### CODE REVIEW

**Comment by raghunayyar** [comment]
:+1:

**Comment by georgehrke** [comment]
rebased

**Comment by raghunayyar** [comment]
:D

**Comment by jancborchardt** [comment]
@georgehrke always always @mention the person who opened the original issue (and every community person who also asked for it) in the pull request and ask them to review. Otherwise it will always fall back to us. :)

**Pull request merged**
