### PR TITLE
Add css lint to travis.

### PR DESCRIPTION
**Pull request by tcitworld**
Yes, I like to lint. Your opinion ?

### CODE REVIEW

**Comment by raghunayyar** [comment]
:+1:

**Comment by tcitworld** [comment]
Just need to test that the build fails correctly.

**Comment by tcitworld** [comment]
It's fine.

**Comment by georgehrke** [comment]
Would it be possible to add a grunt command for `./node_modules/stylelint/dist/cli.js ../css/*.css` ?

**Comment by tcitworld** [comment]
There already is one : `grunt postcss` (I anticipated eventual extra uses of postcss). However right now it doesn't return a proper failure, it just shows warnings. 
Maybe it can be configured instead of calling stylelint this way. But we can also get rid of postcss and use `grunt-stylelint` directly.

**Pull request merged**
