### PR TITLE
use MKCOL instead of MKCALENDAR

### LINKED ISSUE #398: use MKCOL instead of MKCALENDAR
JS issue:

```
MKCALENDAR http://cloud.jancborchardt.net/remote.php/dav/calendars/jan/events/
405 (Request not allowed)
in client.js line 183 
```

@georgehrke any idea?

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/calendar/issues/398

### CODE REVIEW

**Comment by georgehrke** [comment]
@jancborchardt This should fix the creating calendar issue you had. Please try on your server if possible :)

**Comment by jancborchardt** [comment]
Great, works now! :) :+1:

**Comment by jancborchardt** [comment]
Merge? :)

**Comment by georgehrke** [comment]
Yes, I just rebased.

but NPM is making problems again ...

**Comment by georgehrke** [comment]
anyway, tests pass locally, merge

**Pull request merged**
