### PR TITLE
Fixes overflowing table in Firefox

### LINKED ISSUE #472: Week/day selection is overlapping with calendar
As it can be seen on the right.

PS: Awesome improvements in v1.1! The left panel has greatly improved. Love the circular display of the calendar color. :smiley:

### PR DESCRIPTION
**Pull request by raghunayyar**
Fixes #472.
This is a firefox specific issue. Please review : @jancborchardt, @georgehrke and @SamEliotFisher.

### CODE REVIEW

**Comment by georgehrke** [comment]
please don't assign people when they should review.
Everyone is eligible to review PRs :)
Just ping them.

**Comment by raghunayyar** [comment]
Aah, sure.

**Comment by georgehrke** [comment]
CSS Lint says no
https://travis-ci.org/owncloud/calendar/jobs/149722311#L1352

**Comment by raghunayyar** [comment]
Forced pushed the fix.

**Comment by georgehrke** [comment]
works like a charm 👍

**Pull request merged**
