### PR TITLE
Get rid of php

### PR DESCRIPTION
**Pull request by georgehrke**
Get rid of all the php :cry: 
But at least it's for a good.

### CODE REVIEW

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/calendar-rework/issues/88

**Comment by DeepDiver1975** [comment]
> fixes #88

merged

**Comment by georgehrke** [comment]
awesome, will rebase this branch asap

**Comment by raghunayyar** [comment]
travis is failing..

**Comment by raghunayyar** [comment]
:+1:

**Pull request merged**
