### PR TITLE
Fixes on LAST-MODIFIED and DTSTAMP

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- Update LAST-MODIFIED property on each and every change
- Update DTSTAMP property together with LAST-MODIFIED
- Use UTC on LAST-MODIFIED, DTSTAMP and CREATED

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
[calendar.tar.gz](https://github.com/owncloud/calendar/files/2377056/calendar.tar.gz)

**Comment by DeepDiver1975** [comment]
[calendar.tar.gz](https://github.com/owncloud/calendar/files/2379113/calendar.tar.gz)

**Comment by Julian1998** [comment]
Does it also fix https://github.com/owncloud/calendar/issues/943 ?

**Comment by DeepDiver1975** [comment]
> Does it also fix #943 ?

yes - fixes #943

**Comment by Julian1998** [comment]
#943

**Comment by Aceto1** [comment]
This probably fixes #659 too, right?

**Comment by DeepDiver1975** [comment]
> This probably fixes #659 too, right?

indeed - thx

**Pull request merged**
