### PR TITLE
Removing Font-Awesome

### PR DESCRIPTION
**Pull request by raghunayyar**
Currently we have all icons in core so yes, we can happily remove fa,

cc @jancborchardt @georgehrke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Wow, that’s a lot of code for a few icons. Glad we’re getting rid of it. :+1:

**Comment by raghunayyar** [comment]
@jancborchardt I am glad this repository has started to take some shape.

**Comment by jancborchardt** [comment]
Hope you’ll integrate with the core CalDAV soon. :)

**Comment by georgehrke** [comment]
> Hope you’ll integrate with the core CalDAV soon. :)

We sure will! :)

**Comment by georgehrke** [comment]
:+1:

**Comment by georgehrke** [comment]
partly fixes https://github.com/owncloud/calendar-rework/issues/33

**Pull request merged**
