### PR TITLE
query default timezone on start

### LINKED ISSUE #142: Error when trying to create an event and debug output in public/app.js
https://github.com/owncloud/calendar-rework/blob/c26a361f058e25d2778e7ab184614762f0f10ed0/js/public/app.js#l2409

---

I also get an error, which blocks me from creating any events:

> `Object {kind: "timezone_missing", missing_timezone: "Europe/Berlin"}`

```
(anonymous function)    @   angular.js?v=27b72f67cd10cc5f4da167e54ee07a9d:12722
(anonymous function)    @   angular.js?v=27b72f67cd10cc5f4da167e54ee07a9d:9490
Scope.$apply    @   angular.js?v=27b72f67cd10cc5f4da167e54ee07a9d:16356
(anonymous function)    @   calendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:30
trigger @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:8300
fc.View.Class.extend.trigger    @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:6627
fc.View.Class.extend.reportSelection    @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:7311
CellDragListener.listenStop @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:3158
fc.DragListener.Class.extend.trigger    @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:2137
fc.DragListener.Class.extend.listenStop @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:2129
DragListener.extend.listenStop  @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:2440
fc.DragListener.Class.extend.stopListening  @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:2122
fc.DragListener.Class.extend.mouseup    @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:2071
(anonymous function)    @   fullcalendar.js?v=27b72f67cd10cc5f4da167e54ee07a9d:760
x.event.dispatch    @   jquery.min.js?v=27b72f67cd10cc5f4da167e54ee07a9d:5
v.handle    @   jquery.min.js?v=27b72f67cd10cc5f4da167e54ee07a9d:5
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #142 

please review @nickvergessen

### CODE REVIEW

**Comment by georgehrke** [comment]
also @raghunayyar

**Comment by georgehrke** [comment]
this will go into alpha1

**Comment by nickvergessen** [comment]
Still happens :(

**Comment by georgehrke** [comment]
Can you check the network console if your browser queries a Berlin.ics?

**Comment by nickvergessen** [comment]
It does, the request has status 200, but the response is empty

**Comment by nickvergessen** [comment]
Now I went through it with the debugger, response is OK,
but the error persists:
```
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
```

**Comment by georgehrke** [comment]
What browser do you use?
I can't reproduce it anymore when I apply this pr.

**Comment by nickvergessen** [comment]
Right, the checkout of the branch failed, I'm sorry.

Works now :+1:

**Pull request merged**
