### PR TITLE
move to docker based infra

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by georgehrke** [comment]
travis is failing

**Comment by DeepDiver1975** [comment]
> travis is failing

yes - no clue why - bloody python ...

**Comment by DeepDiver1975** [comment]
hmmm ... looks like apache setup requires sudo .... let's postpone this until we have a better understanding ...

**Comment by DeepDiver1975** [comment]
looks like this is not possible using docker based infra

**Pull request closed without merging**
