### PR TITLE
Exception on 4byte utf-8 characters in local db

### LINKED ISSUE #20: Throw exception when adding objects containing emojis to database backend
emojis and other 4 byte unicode characters

### PR DESCRIPTION
**Pull request by codeling**
Should fix #20.
Not tested except for unit tests yet (@georgehrke what API
Also need to elaborate create/update tests for non-error / other error cases.

### CODE REVIEW

**Comment by raghunayyar** [comment]
@codeling is this is WIP or a complete PR?

**Comment by codeling** [comment]
Should be complete but have not had a chance to test except for unit tests

**Comment by DeepDiver1975** [comment]
Instead of throwing an exception you could also encode the strings before writing them to the db.

**Comment by codeling** [comment]
@DeepDiver1975 is that how it's done in core? How would it be encoded best?

**Comment by codeling** [comment]
@DeepDiver1975 any thoughts?
@raghunayyar @georgehrke sorry extremely busy otherwise at the moment, didn't have time yet to look more into testing this

**Comment by DeepDiver1975** [comment]
> is that how it's done in core?

As of today core has no mechanism to take care about this.



> How could it be encoded best?

Something we need to look into - thb

**Comment by georgehrke** [comment]
@DeepDiver1975 IIRC you once suggested url encoding.
Yet another question is how to handle existing objects.
Encode all on upgrade?

**Comment by DeepDiver1975** [comment]
> Encode all on upgrade?

seems so

**Comment by georgehrke** [comment]
obsolete here, still very relevant in https://github.com/owncloud/core/issues/20047

>> Encode all on upgrade?

> seems so

Moving to the dav app seems a good opportunity to do so ;)

**Pull request closed without merging**
